import "~/styles/globals.css";

import type { Metadata } from "next";
import { Geist } from "next/font/google";

import { Header } from "~/components/Header";
import { ThemeProvider } from "~/components/ThemeProvider";
import { ThemeStylesheets } from "~/components/ThemeStylesheets";
import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
    subsets: ["latin"],
    variable: "--font-geist-sans",
});

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html
            className={`${geist.variable}`}
            lang="en"
            suppressHydrationWarning
        >
            <head>
                <link
                    href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/styles/github.min.css"
                    rel="stylesheet"
                />

                <script
                    src="https://cdn.jsdelivr.net/npm/diff2html/bundles/js/diff2html-ui.min.js"
                    type="text/javascript"
                ></script>
            </head>
            <body>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                >
                    <Header />
                    <ThemeStylesheets />
                    <TRPCReactProvider>{children}</TRPCReactProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
