/**
 * Regenerates `src/components/markdown/code-language-map.ts`.
 *
 * The markdown renderer highlights fenced code blocks with
 * `react-syntax-highlighter`, which runs lowlight over highlight.js v10.
 * lowlight only registers canonical language ids — aliases such as `js`,
 * `ts`, `py` or `html` fail react-syntax-highlighter's
 * `checkForListedLanguage` gate and silently fall back to `highlightAuto`.
 *
 * This script resolves react-syntax-highlighter's *own* lowlight/highlight.js
 * copies (not the app's highlight.js v11 dependency) and emits a tag -> id map
 * that mirrors highlight.js's own language resolution:
 *
 *   - canonical ids always win over aliases (hljs checks `languages` first)
 *   - alias collisions resolve last-registered-wins (hljs alias map semantics)
 *
 * Run with: pnpm generate:code-language-map
 */
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";

const require = createRequire(import.meta.url);

const rshPkg = require.resolve("react-syntax-highlighter/package.json");
const rshRequire = createRequire(rshPkg);

// The lowlight instance react-syntax-highlighter bundles, and its
// highlight.js copy — these are the versions the renderer actually uses.
const lowlightPkg = rshRequire.resolve("lowlight/package.json");
const lowlightDir = dirname(lowlightPkg);
const lowlightRequire = createRequire(lowlightPkg);
const hljs = lowlightRequire("highlight.js");

// lowlight/index.js registers every language in order; that order drives
// alias last-wins resolution, so read it from the source of truth.
const lowlightIndex = readFileSync(join(lowlightDir, "index.js"), "utf8");
const ids = [...lowlightIndex.matchAll(/registerLanguage\(\s*'([^']+)'/g)].map(
    (m) => m[1] ?? "",
);

const aliases = new Map<string, string>();
const canonical = new Set<string>();
for (const id of ids) {
    canonical.add(id);
    const def = lowlightRequire(`highlight.js/lib/languages/${id}`);
    const definition = typeof def === "function" ? def(hljs) : def;
    for (const alias of definition?.aliases ?? []) {
        aliases.set(alias, id);
    }
}

const map = new Map<string, string>();
// Aliases first, last-registered-wins (matches hljs's alias map).
for (const [alias, id] of aliases) {
    map.set(alias, id);
}
// Canonical ids override aliases (hljs checks `languages` before `aliases`).
for (const id of canonical) {
    map.set(id, id);
}

const entries = [...map.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([tag, id]) => `    "${tag}": "${id}",`)
    .join("\n");

const out = `// AUTO-GENERATED by scripts/generate-code-language-map.ts — DO NOT EDIT.
// Regenerate with: pnpm generate:code-language-map
//
// Maps markdown code-fence language tags (the part after \`language-\` in the
// className) to the canonical highlight.js language ids that lowlight registers
// for react-syntax-highlighter. Without this, tags like \`js\` or \`html\` miss
// react-syntax-highlighter's checkForListedLanguage gate and fall back to
// unreliable auto-detection.
//
// Resolution mirrors highlight.js: canonical ids win over aliases, and
// alias collisions resolve last-registered-wins (e.g. \`ls\` -> livescript).

export const CODE_LANGUAGE_TAGS: Record<string, string> = {
${entries}
};
`;

const target = new URL(
    "../src/components/markdown/code-language-map.ts",
    import.meta.url,
);
writeFileSync(target, out);
console.log(
    `wrote ${map.size} entries (${canonical.size} canonical, ${
        map.size - canonical.size
    } aliases) to ${target.pathname}`,
);
