// Bakes the route table (src/utils/extension-routes.ts) into the extension so a
// service worker can decide redirects without a network round trip. Re-run
// after touching the table: pnpm generate:extension-routes
import { writeFileSync } from "node:fs";
import {
    EXTENSION_EXIT_PARAM,
    EXTENSION_REQUEST_HEADER,
    EXTENSION_ROUTE_TABLE_PATH,
    serializeExtensionRouteTable,
} from "../src/utils/extension-routes";

const output = `// Generated by scripts/generate-extension-routes.ts -- do not edit by hand.
globalThis.NEOSRC_ROUTE_BUNDLE = {"path":${JSON.stringify(
    EXTENSION_ROUTE_TABLE_PATH,
)},"exitParam":${JSON.stringify(EXTENSION_EXIT_PARAM)},"header":${JSON.stringify(
    EXTENSION_REQUEST_HEADER,
)},"table":${serializeExtensionRouteTable()}};
`;

const target = new URL("../extension/routes.generated.js", import.meta.url);
writeFileSync(target, output);
console.log(`Wrote ${target.pathname}`);
